<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    /**
     * The table associated with the model.
     */
    protected $table = 'ADMIN';

    /**
     * The primary key associated with the table.
     */
    protected $primaryKey = 'adminID';

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'adminUser',
        'adminPass',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
        'adminPass',
    ];

    /**
     * Get the password for authentication.
     */
    public function getAuthPassword()
    {
        return $this->adminPass;
    }

    /**
     * Get the name of the unique identifier for the user.
     */
    public function getAuthIdentifierName()
    {
        return 'adminID';
    }

    /**
     * Get the unique identifier for the user.
     */
    public function getAuthIdentifier()
    {
        return $this->adminID;
    }

    /**
     * Get reports generated by this admin.
     */
    public function reports()
    {
        return $this->hasMany(Report::class, 'adminID', 'adminID');
    }
}
